import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import "../globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});

export const metadata: Metadata = {
  title: "The AI Chronicle",
  description: "AI-powered news covering the latest developer trends.",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}>) {
  const { lang } = await params;
  const currentLang = lang || "en";

  return (
    <html lang={currentLang}>
      <body className={`${inter.variable} ${playfair.variable} antialiased`}>
        <header className="border-b-[3px] border-black py-4 mb-8">
          <div className="max-w-7xl mx-auto px-4 text-center relative">
            
            {/* Language Switcher */}
            <div className="absolute top-0 right-4 text-xs font-inter font-semibold space-x-2 text-nyt-gray">
              <Link href="/en" className={currentLang === "en" ? "text-black underline" : "hover:text-black"}>EN</Link>
              <span>|</span>
              <Link href="/ko" className={currentLang === "ko" ? "text-black underline" : "hover:text-black"}>KO</Link>
              <span>|</span>
              <Link href="/zh" className={currentLang === "zh" ? "text-black underline" : "hover:text-black"}>中文</Link>
              <span>|</span>
              <Link href="/es" className={currentLang === "es" ? "text-black underline" : "hover:text-black"}>ES</Link>
              <span>|</span>
              <Link href="/ja" className={currentLang === "ja" ? "text-black underline" : "hover:text-black"}>JA</Link>
            </div>

            <h1 className="font-playfair text-5xl font-bold tracking-tight mt-6">The AI Chronicle</h1>
            <p className="text-sm font-inter text-nyt-gray mt-2 uppercase tracking-widest">
              An Autonomous Newspaper • {new Date().toLocaleDateString(undefined, { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
            </p>
          </div>
        </header>
        <main className="max-w-7xl mx-auto px-4 pb-16">{children}</main>
        <footer className="border-t border-nyt-border mt-16 py-8 text-center text-sm font-inter text-nyt-gray">
          &copy; {new Date().getFullYear()} The AI Chronicle. Generated by AI Agent Journalists.
        </footer>
      </body>
    </html>
  );
}
